### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by dtomvan** [samodostal/is-prime-online.nvim#1]
My config:
```lua
    use {
        'samodostal/is-prime-online.nvim',
        requires = { 'nvim-lua/plenary.nvim' },
        config = function()
            require('is-prime-online').setup {
                source = 'twitch',
                streamer_name = 'ThePrimeagen',
                refresh_interval_in_seconds = 60,
            }

            local timer = vim.loop.new_timer()
            timer:start(
                1000,
                20000,
                vim.schedule_wrap(function()
                    local status = require('is-prime-online').status()
                    if status == true and vim.g.PRIME_STATUS ~= 1 then
                        vim.notify '🟢 Prime is online!'
                        vim.g.PRIME_STATUS = 1
                    elseif status == false and vim.g.PRIME_STATUS == 1 then
                        vim.notify '🔴 Prime is offline.'
                        vim.g.PRIME_STATUS = 0
                    end
                end)
            )
        end,
    }
```

Packer returns:   `Config for is-prime-online.nvim took 330.372094ms`
Sometimes even neovim will hang for a couple of seconds.

**Comment by samodostal** [comment]
Hey, sorry for replying late.
Where do you get the config startup time from? I am not that familiar with packer, and I couldn't find an easy way to get it. On my machine I didn't see a slow down when using this plugin, but if it the startup time is around 300ms I don't think I would notice it.

By the way, instead of creating a new timer that checks every 20 seconds, you can use the callback function like this:
```lua
require("is-prime-online").setup({
  source = "twitch",
  streamer_name = "thePrimeagen",
  refresh_interval_in_seconds = 20
  callback_on_live = function()
    vim.notify '🟢 Prime is online!'
  end,
})
```

**Comment by dtomvan** [comment]
To answer your first question: I used these 2 commands to "profile" the loading of plugins.
```
:PackerCompile profile=true
:q
$ nvim
:PackerProfile
```

To reply to your second point: in the callback_on_live, can you do the same "Prime went offline" message?
Currently, my config also tells me if Prime was online, but went offline.

**Comment by dtomvan** [comment]
Also, the second-slowest plugin in my config loads in 7ms, which is my status line. This does not include any of the other things that are done in my init.lua.

**Comment by samodostal** [comment]
For now I've disabled a call of a function that checks if the twitch command has set-up authentication. It is now much faster (For me 0.4ms). I'll try to make the verification asynchronous in the future.
